language: java

jdk:
  - oraclejdk8
sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - oracle-java8-installer

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false"]; then
      docker build -t biospheere/codebasebot .;
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push biospheere/codebasebot;
      fi